blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/Architecture-Mechanism/community/discussions
    about: Please ask and answer questions here.
